name: Deploy to GitHub Pages

# Chạy mỗi khi có ai đó push code mới lên nhánh main
on:
  push:
    branches: ["main"] # Sửa thành "master" nếu nhánh chính của bạn tên là master
  workflow_dispatch:

# Cấp quyền ghi để push lên Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Cài đặt thư viện
        run: npm install js-yaml

      - name: 4. Chạy script convert từ YAML sang JS
        run: node build-data.js

      - name: 5. Cấu hình Github Pages
        uses: actions/configure-pages@v4

      - name: 6. Upload file để chuẩn bị Deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Upload toàn bộ thư mục hiện tại lên host

      - name: 7. Deploy lên Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
